export const BOOKING_CREATE_REQUEST = 'BOOKING_CREATE_REQUEST';
export const BOOKING_CREATE_SUCCESS = 'BOOKING_CREATE_SUCCESS';
export const BOOKING_CREATE_FAIL = 'BOOKING_CREATE_FAIL';
export const BOOKING_STATUS_RESET = 'BOOKING_STATUS_RESET';

export const USER_BOOKINGS_REQUEST = 'USER_BOOKINGS_REQUEST';
export const USER_BOOKINGS_SUCCESS = 'USER_BOOKINGS_SUCCESS';
export const USER_BOOKINGS_FAIL = 'USER_BOOKINGS_FAIL';

export const BOOKING_ALL_REQUEST = 'BOOKING_ALL_REQUEST';
export const BOOKING_ALL_SUCCESS = 'BOOKING_ALL_SUCCESS';
export const BOOKING_ALL_FAIL = 'BOOKING_ALL_FAIL';
export const BOOKING_ALL_RESET = 'BOOKING_ALL_RESET';

export const BOOKING_APPROVE_REQUEST = 'BOOKING_APPROVE_REQUEST';
export const BOOKING_APPROVE_SUCCESS = 'BOOKING_APPROVE_SUCCESS';
export const BOOKING_APPROVE_FAIL = 'BOOKING_APPROVE_FAIL';
export const BOOKING_APPROVE_RESET = 'BOOKING_APPROVE_RESET';

export const BOOKING_DELETE_REQUEST = 'BOOKING_DELETE_REQUEST';
export const BOOKING_DELETE_SUCCESS = 'BOOKING_DELETE_SUCCESS';
export const BOOKING_DELETE_FAIL = 'BOOKING_DELETE_FAIL';
export const BOOKING_DELETE_RESET = 'BOOKING_DELETE_RESET';
