export const DAY_LIST_REQUEST = 'DAY_LIST_REQUEST';
export const DAY_LIST_SUCCESS = 'DAY_LIST_SUCCESS';
export const DAY_LIST_FAIL = 'DAY_LIST_FAIL';

export const DAY_REQUEST = 'DAY_REQUEST';
export const DAY_SUCCESS = 'DAY_SUCCESS';
export const DAY_FAIL = 'DAY_FAIL';

export const DAY_UPDATE_REQUEST = 'DAY_UPDATE_REQUEST';
export const DAY_UPDATE_SUCCESS = 'DAY_UPDATE_SUCCESS';
export const DAY_UPDATE_FAIL = 'DAY_UPDATE_FAIL';

export const CLEAR_DAY_SUCCESS = 'CLEAR_DAY_SUCCESS';
export const CLEAR_DAY_ERROR = 'CLEAR_DAY_ERROR';
